insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc T-shirt","T-shirt","s",10,27,"images/w1.jpg","very comfortable short T-shirt with blue flowers on the yellow base")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc T-shirt","T-shirt","m",5,27,"images/w1.jpg","very comfortable short T-shirt with blue flowers on the yellow base")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc T-shirt","T-shirt","l",10,27,"images/w1.jpg","very comfortable short T-shirt with blue flowers on the yellow base")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc long sleeve","T-shirt","s",4,39,"images/w2.jpg","yellow long sleeves with button to adjust the sleeve length")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc long sleeve","T-shirt","m",15,39,"images/w2.jpg","yellow long sleeves with button to adjust the sleeve length")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc long sleeve","T-shirt","l",0,39,"images/w2.jpg","yellow long sleeves with button to adjust the sleeve length")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc long sleeve","T-shirt","xl",25,39,"images/w2.jpg","yellow long sleeves with button to adjust the sleeve length")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Office Lady dress","dress","s",4,57,"images/w3.jpg","black office lady dress, looks slim and formal")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Office Lady dress","dress","m",0,57,"images/w3.jpg","black office lady dress, looks slim and formal")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Office Lady dress","dress","l",20,57,"images/w3.jpg","black office lady dress, looks slim and formal")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Office Lady dress","dress","xl",7,27,"images/w3.jpg","black office lady dress, looks slim and formal")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc T-shirt","T-shirt","s",7,23,"images/w4.jpg","green T-shirt with cute magic picture on it")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc T-shirt","T-shirt","m",27,23,"images/w4.jpg","green T-shirt with cute magic picture on it")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc T-shirt","T-shirt","l",37,23,"images/w4.jpg","green T-shirt with cute magic picture on it")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc T-shirt","T-shirt","xl",15,23,"images/w4.jpg","green T-shirt with cute magic picture on it")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc suit","pajamas","s",2,34,"images/w5.jpg","very comfortable one-piece suit, works for both home and outdoors")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc suit","pajamas","m",22,34,"images/w5.jpg","very comfortable one-piece suit, works for both home and outdoors")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc suit","pajamas","l",12,34,"images/w5.jpg","very comfortable one-piece suit, works for both home and outdoors")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Bbc suit","pajamas","xl",2,34,"images/w5.jpg","very comfortable one-piece suit, works for both home and outdoors")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc dress","dress","s",13,79,"images/w6.jpg","dark pattern professional dress")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc dress","dress","m",3,79,"images/w6.jpg","dark pattern professional dress")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc dress","dress","l",18,79,"images/w6.jpg","dark pattern professional dress")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc dress","dress","xl",23,79,"images/w6.jpg","dark pattern professional dress")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc short T-shirt","T-shirt","s",5,19,"images/w7.jpg","black short T-shirt with a sentence - look at these shoes ")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc short T-shirt","T-shirt","m",27,19,"images/w7.jpg","black short T-shirt with a sentence - look at these shoes ")		
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc short T-shirt","T-shirt","l",38,19,"images/w7.jpg","black short T-shirt with a sentence - look at these shoes ")		
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc short T-shirt","T-shirt","xl",41,19,"images/w7.jpg","black short T-shirt with a sentence - look at these shoes ")		
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc camisole","camisole","s",25,13,"images/w8.jpg","camisole with a black stripe and a green background")		
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc camisole","camisole","m",15,13,"images/w8.jpg","camisole with a black stripe and a green background")		
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc camisole","camisole","l",35,13,"images/w8.jpg","camisole with a black stripe and a green background")		
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc camisole","camisole","xl",5,13,"images/w8.jpg","camisole with a black stripe and a green background")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","s",24,32,"images/w9.jpg","cartoon T-shirt")		
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","m",4,32,"images/w9.jpg","cartoon T-shirt")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","l",2,32,"images/w9.jpg","cartoon T-shirt")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","xl",1,32,"images/w9.jpg","cartoon T-shirt")			

insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc T-shirt","T-shirt","s",1,28,"images/m1.jpg","men cartoon style short T-shirt")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc T-shirt","T-shirt","m",10,28,"images/m1.jpg","men cartoon style short T-shirt")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc T-shirt","T-shirt","l",21,28,"images/m1.jpg","men cartoon style short T-shirt")	
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc T-shirt","T-shirt","xl",18,28,"images/m1.jpg","men cartoon style short T-shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc sport pants","pants","s",41,58,"images/m2.jpg","men blue sport style long pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc sport pants","pants","m",0,58,"images/m2.jpg","men blue sport style long pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc sport pants","pants","l",4,58,"images/m2.jpg","men blue sport style long pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Abc sport pants","pants","xl",22,58,"images/m2.jpg","men blue sport style long pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc T-shirt","T-shirt","s",3,48,"images/m3.jpg","men green and black sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc T-shirt","T-shirt","m",23,48,"images/m3.jpg","men green and black sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc T-shirt","T-shirt","l",8,48,"images/m3.jpg","men green and black sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc T-shirt","T-shirt","xl",18,48,"images/m3.jpg","men green and black sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long sleeve","T-shirt","s",2,51,"images/m4.jpg","men light green long sleeve casual wear")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long sleeve","T-shirt","m",10,51,"images/m4.jpg","men light green long sleeve casual wear")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long sleeve","T-shirt","l",3,51,"images/m4.jpg","men light green long sleeve casual wear")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long sleeve","T-shirt","xl",3,51,"images/m4.jpg","men light green long sleeve casual wear")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long pants","pants","s",1,89,"images/m5.jpg","men light grey long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long pants","pants","m",10,89,"images/m5.jpg","men light grey long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long pants","pants","l",21,89,"images/m5.jpg","men light grey long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA001","Bbc long pants","pants","xl",5,89,"images/m5.jpg","men light grey long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc long pants","pants","s",10,69,"images/m6.jpg","men light jeans long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc long pants","pants","m",1,69,"images/m6.jpg","men light jeans long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc long pants","pants","l",1,69,"images/m6.jpg","men light jeans long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc long pants","pants","xl",10,69,"images/m6.jpg","men light jeans long business professional pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc short pants","pants","s",10,43,"images/m7.jpg","men bright green short sport style pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc short pants","pants","m",10,43,"images/m7.jpg","men bright green short sport style pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc short pants","pants","l",10,43,"images/m7.jpg","men bright green short sport style pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc short pants","pants","xl",1,43,"images/m7.jpg","men bright green short sport style pants")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc polo shirt","T-shirt","s",10,36,"images/m8.jpg","men old red with white dot short sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc polo shirt","T-shirt","m",1,36,"images/m8.jpg","men old red with white dot short sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc polo shirt","T-shirt","l",30,36,"images/m8.jpg","men old red with white dot short sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"PA002","Abc polo shirt","T-shirt","xl",10,36,"images/m8.jpg","men old red with white dot short sport style polo shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc shorts","shorts","s",1,16,"images/m9.jpg","men light yellow sport style shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc shorts","shorts","m",3,16,"images/m9.jpg","men light yellow sport style shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc shorts","shorts","l",8,16,"images/m9.jpg","men light yellow sport style shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc shorts","shorts","xl",1,16,"images/m9.jpg","men light yellow sport style shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc waistcoat","waistcoat","s",3,9,"images/m10.jpg","men purple sport style tights waistcoat")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc waistcoat","waistcoat","m",38,9,"images/m10.jpg","men purple sport style tights waistcoat")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc waistcoat","waistcoat","l",7,9,"images/m10.jpg","men purple sport style tights waistcoat")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Abc waistcoat","waistcoat","xl",1,9,"images/m10.jpg","men purple sport style tights waistcoat")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Bbc long sleeve","T-shirt","s",30,25,"images/m11.jpg","men yellow formal long sleeve shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Bbc long sleeve","T-shirt","m",3,25,"images/m11.jpg","men yellow formal long sleeve shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Bbc long sleeve","T-shirt","l",2,25,"images/m11.jpg","men yellow formal long sleeve shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA001","Bbc long sleeve","T-shirt","xl",10,25,"images/m11.jpg","men yellow formal long sleeve shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Abc shorts","shorts","s",7,30,"images/m12.jpg","men wide-striped shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Abc shorts","shorts","m",20,30,"images/m12.jpg","men wide-striped shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Abc shorts","shorts","l",34,30,"images/m12.jpg","men wide-striped shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Abc shorts","shorts","xl",1,30,"images/m12.jpg","men wide-striped shorts")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","s",1,41,"images/m13.jpg","men original college Denim T-shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","m",0,41,"images/m13.jpg","men original college Denim T-shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","l",2,41,"images/m13.jpg","men original college Denim T-shirt")
insert into Product (product_ID,store_ID,productName,kind,size,inventory_amount,price,img,description) values (0,"CA002","Bbc T-shirt","T-shirt","xl",17,41,"images/m13.jpg","men original college Denim T-shirt")
















	
